<a href="https://colab.research.google.com/github/VoTanThinh/ANN/blob/main/ANN(mangthankinhnhantao)2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import Perceptron
x=[[0,0],[0,1],[1,0],[1,1]]
t=[0,1,1,1]
model = Perceptron()                #dạy học
model.fit(x,t)
model.score(x,t)

1.0

In [ ]:
x1=[[-3,-3],[1,1],[13,18],[15,12]]
y1=model.predict(x1)
model.score(x1,y1)
print((y1))

[0 1 1 1]


In [ ]:
from sklearn.linear_model import Perceptron
x1=[[0.5,0.5],[-0.5,0.5],[10,20],[-1,-2]]
y1=model.predict(x1)
model.score(x1,y1)
print(y1)

[1 1 1 0]


In [ ]:
x1=[[-0.5,0.5]]             # dưới 0.5 là 0 và trên 0.5 là 1 đường phân chia đường dữ liệu
y1=model.predict(x1)
model.score(x1,y1)
print((y1))

[1]


In [ ]:
from sklearn.linear_model import Perceptron
x2=[[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
t2=[1,1,0,0]
model = Perceptron()
model.fit(x2,t2)
model.score(x2,t2)

x3=[[0,0],[0,1],[1,0],[1,1]]            # dưới 0.5 là 0 và trên 0.5 là 1 đường phân chia đường dữ liệu
y4=model.predict(x3)
model.score(x3,y4)
print((y4))

[0 0 0 0]


In [ ]:
from pandas.io.formats.format import east_asian_width
# truy xuất tập dữ liệu trên mạng phân loại hoa lan (0,1,2) xem (0,1)                #3 loại 
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split          #dữ liệu train k được dùng để test
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import StandardScaler              #sacle tỉ về cho dữ liệu đều nhau
iris = datasets.load_iris()                 #lấy thông tin từ dữ liệu data của hoa lan   #(150 hàng 4 cột)
x=iris.data                                 
y=iris.target                               
print(x[:5])                            #in ra dữ diệu cần tìm trong khoảng
print(y[:5])

#chia dữ liệu
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)                          #30% test 70%train
sc = StandardScaler()
sc.fit(x_train)    # học tỉ lệ
x_train_std = sc.transform(x_train)     # nhân tỉ lệ đó 
x_test_std = sc.transform(x_test)
print(x_train_std[:5],x_train[:5])   #xuất 2 dữ liệu ra
print(y[:5])
model2 = Perceptron(max_iter=90,eta0=0.9,random_state=0)    #(số lần học max_iter=40laan, eta0(tốc độ học (0-1)),radom_state trạng thái lấy)
model2.fit(x_train_std,y_train)   #
y_pred = model2.predict(x_test_std)   # tien đón giá trị ra
print(y_pred)
print(y_test)
print('độ chính xác mô hình',accuracy_score(y_test,y_pred))  #in ra độ chính xác                                    #sacle thì tỉ lệ tăng lên







[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[[ 0.81113319 -0.06769308  1.16481211  1.29258844]
 [-0.0333185  -0.7340468   0.19999094 -0.26593925]
 [-0.87777019  1.70925018 -1.21886372 -1.30495771]
 [-0.39522637 -1.40040051 -0.0270258  -0.26593925]
 [-0.99840615 -2.28887214 -0.14053418 -0.26593925]] [[6.5 3.  5.8 2.2]
 [5.8 2.7 4.1 1. ]
 [5.1 3.8 1.6 0.2]
 [5.5 2.4 3.7 1. ]
 [5.  2.  3.5 1. ]]
[0 0 0 0 0]
[0 2 2 0 1 1 2 0 0 0 2 0 2 2 0 0 0 1 0 0 1 2 2 2 0 2 1 1 0 0 0 0 0 0 2 2 0
 2 2 0 1 1 1 0 2]
[0 2 2 0 1 1 2 0 1 0 2 0 2 2 0 1 1 1 0 0 1 2 2 1 0 2 1 1 0 1 0 1 0 0 2 2 0
 2 2 1 1 1 1 0 2]
độ chính xác mô hình 0.8444444444444444


In [ ]:
import pandas as pd        #INPUT:LOÀI+CÁC ĐẶC TÍNH
import numpy as np         #OUTPU:GIỚI TÍNH
from pandas.io.formats.format import east_asian_width
# truy xuất tập dữ liệu trên mạng phân loại hoa lan (0,1,2) xem (0,1)                #3 loại 
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split          #dữ liệu train k được dùng để test
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import StandardScaler 
url='crabs.csv'
data= pd.read_csv(url)
x = data['speies']                                 
y = data['sex'] 
k=x.replace(['B','O'],['0','1'])
k.head(20)
z=y.replace(['M','F'],['1','0'])
z.head(20)
                             

#x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)                          #30% test 70%train
#print(x_train_std[:10],x_train[:10])   #xuất 2 dữ liệu ra
#print(y[:10])







0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
Name: sex, dtype: object